Basics:

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print (a) 

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [5]:
#get dimention
b.ndim

2

In [6]:
# get shape
b.shape

(2, 3)

Acsessing elements in lists:

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
#get specific element
a[1,1]

np.int64(9)

In [9]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
#get a specific columb
a[: , 2]

array([ 3, 10])

In [11]:
#get a specifc range
a[0, 1:8:2]

array([2, 4, 6])

In [12]:
#changing element
a[1,3] = 22

a[:, 2] = 54
print (a)

[[ 1  2 54  4  5  6  7]
 [ 8  9 54 22 12 13 14]]


In [13]:
#all zeros matrix
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
#all ones matrix
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [15]:
#any other number
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [16]:
#any other number (full_like)
np.full_like(a,10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [17]:
#any other number (full)
np.full(a.shape,10)


array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [18]:
#random decimal numbers
np.random.rand(4,2)

array([[0.65873229, 0.86981852],
       [0.68744677, 0.50632231],
       [0.21142034, 0.58785914],
       [0.60132327, 0.17811441]])

In [19]:
#random integer numbers
np.random.randint(2,5, size=(3,3))

array([[4, 4, 3],
       [2, 2, 4],
       [3, 4, 2]], dtype=int32)

In [20]:
#the identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
#excersize 1
arr = np.ones((5,5))
print (arr)

zeros = np.zeros((3,3))
print (zeros)
zeros[1,1] = 9
print(zeros)

arr[1:-1,1:-1] = zeros

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
#.copy keeps the values as they are
a = np.array([1,2,3])

b = a.copy()
b[0] = 100

print (a)

[1 2 3]


Mathematics

In [24]:
a = np.array([1,2,3])

In [25]:
a + 2

array([3, 4, 5])

In [26]:
a -2

array([-1,  0,  1])

In [27]:
a * 2

array([2, 4, 6])

In [28]:
a / 2

array([0.5, 1. , 1.5])

In [29]:
b = np.array([1,1,1])
a + b

array([2, 3, 4])

In [30]:
a ** 2

array([1, 4, 9])

In [31]:
#take the sin 
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])